= Lucidworks Kubernetes Workshop

Each lab directory contains detailed instructions to guide your exploration of the concepts covered in the corresponding lesson.

Start by choosing a unique namespace and release name for your Fusion install.

Clone this repository: `git clone https://github.com/lucidworks/lw-k8s-workshop.git`

Create a local branch where you can make changes: `git checkout -b <NAMESPACE>`

Run the `update_lab_vars.sh` script to update all the commands in the labs to use your namespace, release, and GCP project ID.

For instance if my desired namespace is `tjp`, then run:
```
./update_lab_vars.sh -n tjp -p lw-sales
```

__The script simply updates various commands in the lab instructions with your namespace, release, project, and hostname to save you some typing.__

Commit and push your branch so you now have personalized instructions for your namespace.
```
git commit -am "Add namespace branch for NAME"
git push
```

View the README for each lab in github: https://github.com/lucidworks/lw-k8s-workshop/tree/<NAMESPACE>

