== Lab 1: Install Fusion 5 Helm Chart on GKE

In this lab, you'll install Fusion 5 into a unique namespace in a shared GKE cluster. We'll use the cluster you build in this lab for the remaining lessons.

=== Step 0: Join the Workshop Slack Channel

`#lw-k8s-workshop`

=== Step 1: Install the Fusion 5 Helm Chart

Start by cloning the fusion-cloud-native repo:
```
git clone https://github.com/lucidworks/fusion-cloud-native.git
cd fusion-cloud-native
```

*IMPORTANT: If you already have this github repo cloned locally, please do a `git pull` to ensure you have the latest updates.*

Cloning the github repo is preferred so that you can pull in updates to the scripts, but if you are not a git user, then you can download the project: https://github.com/lucidworks/fusion-cloud-native/archive/master.zip. Once downloaded, extract the zip and cd into the `fusion-cloud-native-master` directory.

Start by reading the script using: `./setup_f5_gke.sh --help`

When calling the `setup_f5_gke.sh` script pass `--version 5.0.2` to indicate you want to install version `5.0.2`.

Here's an example for the training cluster in the `proserve` project:
```
./setup_f5_gke.sh -c proserve-trng -p proserve -z us-west1 -n emaq --version 5.0.2
```

The latest script already has version `5.0.3-2` as the default version, but since we want to perform an upgrade after installing to demonstrate how upgrades work with Helm, we'll start with `5.0.2`.

Make sure all the pods are healthy and running by watching the cluster rollout using: `kubectl get pods --watch`

Hit `ctrl-c` once all the pods are running.

The setup script reports the external IP for the Fusion API Gateway service (aka `proxy`), which runs on port 6764.

=== Step 2: Create a New App in the Fusion Admin UI

Login to the Fusion Admin UI using the Gateway address shown by the script and create a new app named `lab1`.

The setup script will display the external IP for your cluster, but you can also do:
```
kubectl --namespace emaq get service proxy -o jsonpath='{.status.loadBalancer.ingress[0].hostname}'
```
The port is `6764`

Use the Fusion Quickstart to index one of the preloaded datasets into your `lab1` app.

__Tip: To launch the Quickstart, click on the *New here? Get started...* link in the upper left__

=== Step 3: Upgrade to Latest Fusion 5.0.3-2

The setup script created a custom values yaml

The setup script created a new shell script named `gke_proserve-trng_emaq_fusion_upgrade.sh` in the `fusion-cloud-native` directory.

Edit the update script to set the `CHART_VERSION` variable in your upgrade to `5.0.3-2` (the latest version) and run the upgrade script to upgrade your cluster to the latest updates for 5.0.2

Watch the pods as the upgrade rolls out across the cluster. `kubectl get pods --watch`.

Check the Docker image versions running in the namespace using:
```
kubectl get po -o jsonpath='{..image}'  | tr -s '[[:space:]]' '\n' | sort | uniq
```

__Pro Tip: Add your custom values yaml files and upgrade script to: https://github.com/lucidworks/shared-k8s-internal __

If you notice the admin service does not come up successfully after running the upgrade, you can kill it `k delete po <ID>`.
This is due to a minor bug in the admin service when only running 1 Solr pod, the admin service can get hung if Solr upgrades at the same time as the admin service (will be fixed 5.1).

=== Step 4: Verify your Installation

Create an alias for `kubectl`:

```
alias k=kubectl
```

Familiarize yourself with the commands used to verify the installation:
https://github.com/lucidworks/fusion-cloud-native#verifying

=== Step 5: Get a JWT from the Gateway

Lastly, let's request a JWT from the Gateway and decode it so you understand how Fusion 5 stateless sessions work

```
curl -u admin:<PASSWORD> -XPOST http://<PROXY_IP>:6764/oauth2/token
```

Copy the `access_token` value returned from the POST request.

Decode the JWT using: https://jwt.io/

Should see something like this:
```
{
  "sub": "admin",
  "permissions": [],
  "scope": [
    "openid",
    "email",
    "profile"
  ],
  "iss": "http://proxy:6764/oauth2/default",
  "realm": "native",
  "exp": 1579970817,
  "userId": "1ad40099-9219-4b00-b727-102703df3ebb",
  "iat": 1579969017,
  "permissions_vs": 489,
  "authorities": [
    "admin"
  ]
}
```

