== Lab 2: Install Fusion 5 Helm Chart on GKE

In this lab, you'll install the latest version of the Fusion 5 Helm chart into a unique namespace in a shared GKE cluster.
We'll use the Fusion 5 deployment you build in this lab for the subsequent labs in this course.

You're encouraged to team up in groups of 2 or 3 to work through the lab exercises and self-assessments.

=== Step 1: Verify gcloud access

If you've done the pre-work, then you should already have `gcloud` setup.

Execute the following command to ensure you're authenticated to GCP using your *Lucidworks* account:
```
gcloud config get-value core/account
```

If you do not see your Lucidworks email address as output from the previous command, then make sure you've installed the gcloud command-line tools (https://cloud.google.com/sdk/docs/quickstarts) and authenticated to GCP.
```
gcloud init
gcloud components update
gcloud config set core/account YOUR_LUCIDWORKS_EMAIL
gcloud components install kubectl
```

Verify your `kubectl` version is at least 1.13.x:
```
kubectl version
```

=== Step 2: Verify Helm v3

Make sure you have Helm v3 installed! *Do not try to install Fusion 5 with Helm v2!*

Run:
```
helm version --short
```

If your version does not start with with `v3.`, please do an upgrade. On a Mac, do:
```
brew upgrade kubernetes-helm
```

If not running on Mac, refer to this page for instructions on installing Helm v3 for your OS: https://helm.sh/docs/intro/install/

=== Step 3: Choose the right shared GKE cluster

[width="70%",cols="4,3,5",options="header"]
|=========================================================
|Org|GCP Project|Cluster Name
|PS|proserve|proserve-trng
|Sales/SE|lw-sales|lw-sales-trng
|Support|lw-support-team|lw-support-team-trng
|Training & Docs|training-and-docs|training-and-docs-trng
|All Others|lw-sales|lw-sales-trng
|=========================================================

=== Step 4: Choose a unique namespace for your install

Start by choosing a unique namespace for your Fusion install, such as the first 3 characters of your first and last name.

A namespace should only contain lowercase letters (a-z), digits (0-9), underscore, or dash. No periods allowed.

Download: <TODO: LINK>

*source* the `export_lab_vars.sh` script in your shell to export environment variables used by commands in the labs.

For instance if my desired namespace is `tjp` and I'm using the `lw-sales` project, then I would run:
```
cd lab2
source ./export_lab_vars.sh -n tjp -p lw-sales
```

__The script simply exports the `LW_K8S_CLUSTER`, `LW_K8S_NAMESPACE`, `LW_K8S_RELEASE`, and `LW_K8S_GCP_PROJECT` vars for your cluster to save you some typing / copy-pasting in the labs.__

To verify you have access to the training cluster and GCP project, run the following command:
```
gcloud config set compute/zone us-west1
gcloud config set project ${LW_K8S_GCP_PROJECT}
gcloud container clusters get-credentials ${LW_K8S_CLUSTER}
kubectl config current-context
```
Watch for errors and correct as indicated.

=== Step 5: Install the Fusion 5 Helm Chart

You are now ready to install Fusion 5 in the Kubernetes cluster.

Start by cloning the fusion-cloud-native repo:
```
git clone https://github.com/lucidworks/fusion-cloud-native.git
cd fusion-cloud-native
```

*IMPORTANT: If you already have this github repo cloned locally, please do a `git pull` to ensure you have the latest updates.*

.Clone a Github Repo... What the ?
****
So you might be asking yourself, why do we need to clone a github repo to install Fusion 5? The simple answer here is *velocity*!
As you can see from the commit history in this repo, we've been iterating on these scripts and docs rapidly over the past several months. They've finally reached a stable state.
Coming with Fusion 5.1, there will be a downloadable zip containing the installation scripts on our Web site. However, for Lucidworks employees, we recommend you always work with
the latest scripts by pulling from github.
****

Cloning the github repo is preferred so that you can pull in updates to the scripts, but if you are not a git user, then you can download the project: https://github.com/lucidworks/fusion-cloud-native/archive/master.zip.
Once downloaded, extract the zip and cd into the `fusion-cloud-native-master` directory.

*In the same shell where you sourced the `export_lab_vars.sh` script, `cd` into the `fusion-cloud-native` directory for installing Fusion 5*

Start by reading the script usage to get a sense for the various options: `./setup_f5_gke.sh --help`

When you're ready to install, run this command:
```
./setup_f5_gke.sh -c ${LW_K8S_CLUSTER} -p ${LW_K8S_GCP_PROJECT} -n ${LW_K8S_NAMESPACE}
```

Make sure all the pods are healthy and running by watching the cluster rollout using: `kubectl get pods --watch`

Hit `ctrl-c` once all the pods are running.

Once completed, the setup script reports the external IP for the Fusion API Gateway service (aka `proxy`), which runs on port 6764.

.Any and All Kubernetes
****
The `setup_f5_gke.sh` eventually just calls `helm` to install the Fusion 5 Helm chart. Consequently, to install Fusion 5 on any Kubernetes, you can skip the setup scripts and just use `helm` directly, for example:
```
helm upgrade "${LW_K8S_NAMESPACE}" lucidworks/fusion --install \
  --namespace "${LW_K8S_NAMESPACE}" \
  --values "gke_${LW_K8S_CLUSTER}_${LW_K8S_NAMESPACE}_fusion_values.yaml"
```
Lucidworks provides the setup scripts for popular Kubernetes platforms, such as GKE and AKS, to help users that are new to Kubernetes get started quickly.
The other advantage of the setup script is that it creates a custom values yaml file to help you customize your installation.
However, experienced Kubernetes users can skip our scripts and just use Helm directly as shown above.
****

=== Step 6: Create a New App in the Fusion Admin UI

Login to the Fusion Admin UI using the Gateway address shown by the script and create a new app named `lab2`.

The setup script will display the external IP for your cluster, but you can also run the following command to lookup the Gateway IP:
```
kubectl --namespace ${LW_K8S_NAMESPACE} get service proxy -o jsonpath='{.status.loadBalancer.ingress[0].ip}'
```
The port is `6764`

Export the external IP for your Gateway pod:
```
export LW_K8S_GATEWAY_IP=$(kubectl --namespace ${LW_K8S_NAMESPACE} get service proxy -o jsonpath='{.status.loadBalancer.ingress[0].ip}')
```

__NOTE: For this course, we're not using K8s ingress__

*If the Fusion UI does not prompt you to set an initial admin password and simply redirects you to a login screen, then this means Solr and/or the admin service is not running in your cluster yet. Raise your hand if this occurs and we'll help you troubleshoot.*

Use the Fusion Quickstart to index one of the preloaded datasets into your `lab2` app.

__Tip: To launch the Quickstart, click on the *New here? Get started...* link in the upper left__

=== Step 7: Verify your Installation

Create an alias for `kubectl`:

```
alias k=kubectl
```

Familiarize yourself with the commands used to verify the installation:
https://github.com/lucidworks/fusion-cloud-native#verifying

=== Step 8: Get a JWT from the Gateway

Lastly, let's request a JWT from the Gateway and decode it so you understand how Fusion 5 stateless sessions work.

```
curl -u admin:<PASSWORD> -XPOST "http://${LW_K8S_GATEWAY_IP}:6764/oauth2/token"
```

Copy the `access_token` value returned from the POST request.

Decode the JWT using: https://jwt.io/

Should see something like this:
```
{
  "sub": "admin",
  "permissions": [],
  "scope": [
    "openid",
    "email",
    "profile"
  ],
  "iss": "http://proxy:6764/oauth2/default",
  "realm": "native",
  "exp": 1579970817,
  "userId": "1ad40099-9219-4b00-b727-102703df3ebb",
  "iat": 1579969017,
  "permissions_vs": 489,
  "authorities": [
    "admin"
  ]
}
```

The JWT decoder will report an error related to the public key; this is benign and simply due to the public key Fusion uses to digitally sign JWTs is not exposed externally.

The JWT is used as a session cookie for the Fusion Admin UI.
